apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: FolderIAMMember
metadata:
  name: crossplane-preprod
spec:
  forProvider:
    serviceAccountRef:
      name: example-sa
    role: editor
    folderId: ${data.folderId}
  providerConfigRef:
    name: default
