apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: example-sa
  annotations:
    uptest.upbound.io/pre-delete-hook: testhooks/delete-sa-deps.sh
spec:
  forProvider:
    name: example-sa
  providerConfigRef:
    name: default