apiVersion: ydb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: DatabaseDedicated
metadata:
  name: database1
  annotations:
    uptest.upbound.io/timeout: "180"
spec:
  forProvider:
    location:
    - region:
      - id: ru-central1
    name: test-ydb-dedicated
    networkIdRef:
      name: example-net
    subnetIdsRefs:
          - name: example-subnet-a
          - name: example-subnet-b
          - name: example-subnet-d
    resourcePresetId: medium
    scalePolicy:
    - fixedScale:
      - size: 1
    storageConfig:
    - groupCount: 1
      storageTypeId: ssd
  providerConfigRef:
    name: default
---
apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: example-subnet-b
spec:
  forProvider:
    name: example-subnet-b
    networkIdRef:
      name: example-net
    v4CidrBlocks:
      - 10.0.1.0/24
    zone: ru-central1-b
  providerConfigRef:
    name: default
---
apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: example-subnet-d
spec:
  forProvider:
    name: example-subnet-d
    networkIdRef:
      name: example-net
    v4CidrBlocks:
      - 10.0.3.0/24
    zone: ru-central1-d
  providerConfigRef:
    name: default
