apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: MongodbCluster
metadata:
  name: example-mongodb
  annotations:
    uptest.upbound.io/conditions: 'Ready,Synced'
    uptest.upbound.io/pre-delete-hook: testhooks/delete-mongo-deps.sh
spec:
  forProvider:
    name: example-mongodb
    environment: PRODUCTION
    networkIdRef:
      name: example-net
    clusterConfig:
      - version: "6.0"
    resources:
      - diskSize: 16
        diskTypeId: network-hdd
        resourcePresetId: s2.micro
    maintenanceWindow:
      - type: ANYTIME
    host:
      - zoneId: ru-central1-a
        subnetIdRef:
          name: example-subnet-a
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: mongodb-conn
    namespace: default