apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: default
type: Opaque
data:
  # 12345678
  password: MTIzNDU2Nzg=
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: MongodbUser
metadata:
  name: example-mongo-user
  labels:
    testing.upbound.io/example-name: mongo
spec:
  forProvider:
    name: example-user
    passwordSecretRef:
      name: mongodb
      key: password
      namespace: default
    clusterIdRef:
      name: example-mongodb
    permission:
      - databaseName: database1
        roles:
          - readWrite