apiVersion: v1
kind: Secret
metadata:
  name: mysqlsec
  namespace: default
type: Opaque
data:
  # 12345678
  password: MTIzNDU2Nzg=
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: MySQLCluster
metadata:
  name: example-mysql
  annotations:
    uptest.upbound.io/conditions: 'Ready,Synced'
    uptest.upbound.io/pre-delete-hook: testhooks/delete-mysql-deps.sh
spec:
  forProvider:
    name: example-mysql
    environment: PRESTABLE
    networkIdRef:
      name: example-net
    resources:
      - diskSize: 16
        diskTypeId: network-hdd
        resourcePresetId: s2.micro
    version: "8.0"
    mysqlConfig:
      sql_mode: "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
      max_connections: "100"
      default_authentication_plugin: "MYSQL_NATIVE_PASSWORD"
      innodb_print_all_deadlocks: "true"
    maintenanceWindow:
      - type: WEEKLY
        day: SAT
        hour: 12
    host:
      - zone: ru-central1-a
        subnetIdRef:
          name: example-subnet-a
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: mysql-conn
    namespace: default
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: MySQLUser
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/mysqluser
  labels:
    testing.upbound.io/example-name: mysql
  name: mysql-user1
spec:
  forProvider:
    clusterIdRef:
      name: example-mysql
    connectionLimits:
    - maxConnectionsPerHour: 30
      maxQuestionsPerHour: 10
      maxUpdatesPerHour: 20
      maxUserConnections: 40
    name: user1
    passwordSecretRef:
      name: mysqlsec
      key: password
      namespace: default
    permission:
      - databaseName: db_name
        roles:
          - ALL
  providerConfigRef:
    name: default
