apiVersion: v1
kind: Secret
metadata:
  name: opensearch
  namespace: default
type: Opaque
data:
  # 12345678
  password: MTIzNDU2Nzg=
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: OpensearchCluster
metadata:
  annotations:
    uptest.upbound.io/conditions: 'Ready,Synced'
  name: opensearch-cluster
spec:
  forProvider:
    config:
      - adminPasswordSecretRef:
          key: password
          name: opensearch
          namespace: default
        opensearch:
          - nodeGroups:
              - assignPublicIp: true
                hostsCount: 1
                name: group0
                resources:
                  - diskSize: 10737418240
                    diskTypeId: network-ssd
                    resourcePresetId: s2.micro
                roles:
                  - data
                  - manager
                subnetIdsRefs:
                  - name: example-subnet-a
                zoneIds:
                  - ru-central1-a
    environment: PRESTABLE
    maintenanceWindow:
      - type: ANYTIME
    name: opensearch-cluster
    networkIdRef:
      name: example-net
  writeConnectionSecretToRef:
    name: opensearch-conn
    namespace: default