apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: default
type: Opaque
data:
  # 12345678
  password: MTIzNDU2Nzg=
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: PostgresqlCluster
metadata:
  annotations:
    uptest.upbound.io/conditions: 'Ready,Synced'
    uptest.upbound.io/pre-delete-hook: testhooks/delete-postgres-deps.sh
  name: example-pg
spec:
  forProvider:
    name: example-pg
    environment: PRESTABLE
    networkIdRef:
      name: example-net
    config:
      - version: "15"
        resources:
          - diskSize: 16
            diskTypeId: network-hdd
            resourcePresetId: s2.micro
        postgresqlConfig:
          max_connections: "395"
          enable_parallel_hash: "true"
          vacuum_cleanup_index_scale_factor: "0.2"
          autovacuum_vacuum_scale_factor: "0.34"
          default_transaction_isolation: "TRANSACTION_ISOLATION_READ_COMMITTED"
          shared_preload_libraries: SHARED_PRELOAD_LIBRARIES_AUTO_EXPLAIN
    maintenanceWindow:
      - type: WEEKLY
        day: SAT
        hour: 12
    host:
      - zone: ru-central1-a
        subnetIdRef:
          name: example-subnet-a
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: postgress-conn
    namespace: default
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: PostgresqlUser
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/postgresqluser
  labels:
    testing.upbound.io/example-name: postgres
  name: pg-user1
spec:
  forProvider:
    clusterIdRef:
      name: example-pg
    connLimit: 50
    name: user1
    passwordSecretRef:
      name: postgresql
      key: password
      namespace: default
    permission:
    settings:
      default_transaction_isolation: "read committed"
      log_min_duration_statement: "5000"
  providerConfigRef:
    name: default
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: PostgresqlDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/postgresqldatabase
  labels:
    testing.upbound.io/example-name: postgres
  name: pg-database1
spec:
  forProvider:
    clusterIdRef:
      name: example-pg
    extension:
    - name: uuid-ossp
    - name: xml2
    lcCollate: en_US.UTF-8
    lcType: en_US.UTF-8
    name: db_name
    owner: user1
  providerConfigRef:
    name: default