apiVersion: yandex-cloud.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    upjet.upbound.io/manual-intervention: "Created for tests by init script."
spec:
  credentials:
    cloudId: ${data.cloudId}
    folderId: ${data.folderId}
    source: Secret
    secretRef:
      name: yc-creds
      namespace: crossplane-system
      key: credentials