apiVersion: datatransfer.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Transfer
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: "Transfer will actually execute upon creation."
  labels:
    testing.upbound.io/example-name: pgpg_transfer
  name: pgpg-transfer
spec:
  forProvider:
    name: pgpg
    sourceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: pg_source
    targetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: pg_target
    type: SNAPSHOT_AND_INCREMENT
  providerConfigRef:
    name: default
