apiVersion: alb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: HTTPRouter
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/httprouter
  labels:
    testing.upbound.io/example-name: my-router
  name: test-router
spec:
  forProvider:
    labels:
      empty-label: ""
      tf-label: tf-label-value
    name: my-http-router
  providerConfigRef:
    name: default
