apiVersion: resourcemanager.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Folder
metadata:
  name: example-folder
  annotations:
    crossplane.io/external-name: ${data.folderId}
    upjet.upbound.io/manual-intervention: "ObserveOnly doesn't behave well in tests."
spec:
  managementPolicy: ObserveOnly
  forProvider:
    name: crossplane-example
    cloudId: ${data.cloudId}
  providerConfigRef:
    name: default