apiVersion: message.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Queue
metadata:
  name: queue-example
  annotations:
    upjet.upbound.io/manual-intervention: "Requires manual cleanup in case of e2e tests failure."
spec:
  forProvider:
    name: queue-example

    secretKeySecretRef:
      name: sa-key-conn
      namespace: upbound-system
      key: attribute.secret_key

    accessKeyRef:
      name: example-sa-static-key